# Generated by Django 4.2.6 on 2024-01-14 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestblood',
            name='state',
        ),
        migrations.AddField(
            model_name='donor',
            name='last_donate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='requestblood',
            name='patient_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requestblood',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Donate_Blood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('date', models.CharField(blank=True, max_length=100)),
                ('status', models.IntegerField(default=0)),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.bloodgroup')),
            ],
        ),
    ]
