# Generated by Django 4.2.6 on 2024-01-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_requestblood_state_donor_last_donate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestblood',
            name='state',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
