# Generated by Django 4.2.6 on 2023-12-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_requestblood_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='last_donate',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
