# Generated by Django 4.2.6 on 2024-01-14 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_requestblood_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestblood',
            name='state',
        ),
    ]
