# Generated by Django 4.2.6 on 2023-12-24 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_donor_last_donate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate_Blood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('date', models.CharField(blank=True, max_length=100)),
                ('status', models.IntegerField(default=0)),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.bloodgroup')),
            ],
        ),
    ]
